# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install stack (MacOS)
        run: curl -sSL https://get.haskellstack.org/ | sh
        if: matrix.os == 'macos-10.15'

      - name: Install stack (Windows)
        run: choco install haskell-stack
        if: matrix.os == 'windows-2019'

      - name: Cache dependencies (Unix)
        uses: actions/cache@v1
        if: matrix.os != 'windows-2019'
        with:
          path: ~/.stack
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Cache dependencies (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Roaming\stack'
          key: ${{ runner.os }}-store-${{ hashFiles('generator/stack.yaml.lock') }}-${{ hashFiles('generator/generator.cabal') }}

      - name: Cache GHC (Windows)
        uses: actions/cache@v1
        if: matrix.os == 'windows-2019'
        with:
          path: 'C:\Users\runneradmin\AppData\Local\Programs\stack'
          key: ghc-${{ hashFiles('generator/stack.yaml.lock') }}
      - name: Generate
        run: make generate
      - name: Install
        run: yarn
      - name: Percy Test
        run: npx percy exec -- percy snapshot snapshots.yml
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
